// Question pools for the Sacred Pagoda trial. Two difficulty bands, selectable
// via the Kids/Adults toggle on the gate modal:
//   KIDS_QUESTIONS   — general knowledge pitched at roughly ages 10–12
//   ADULTS_QUESTIONS — harder general knowledge for grown-ups
//
// Each entry:
//   q       — the question text
//   choices — 3–4 answer options
//   answer  — index of the correct option in `choices`
//   explain — a one-line explanation shown on the results screen
//
// Edit freely. When the game's AI integration lands, generated questions may be
// used instead; these pools remain the fallback whenever none is available.

export const KIDS_QUESTIONS = [
  { q: "What is the capital city of France?", choices: ["Lyon", "Paris", "Nice", "Marseille"], answer: 1, explain: "Paris is the capital of France." },
  { q: "What is the name of the galaxy we live in?", choices: ["Andromeda", "Milky Way", "Whirlpool", "Pinwheel"], answer: 1, explain: "Our galaxy is the Milky Way." },
  { q: "Which is the closest star to Earth?", choices: ["The Moon", "The Sun", "Polaris", "Alpha Centauri"], answer: 1, explain: "The Sun is the closest star to Earth." },
  { q: "What gas do plants release during photosynthesis?", choices: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 1, explain: "Plants take in carbon dioxide and give out oxygen." },
  { q: "Which is the only mammal capable of true flight?", choices: ["Flying squirrel", "Bat", "Sugar glider", "Owl"], answer: 1, explain: "Bats are the only mammals that can truly fly." },
  { q: "What do you call a group of lions?", choices: ["Herd", "Pack", "Pride", "Flock"], answer: 2, explain: "A group of lions is called a pride." },
  { q: "Which country is home to the Great Wall?", choices: ["Japan", "India", "China", "Korea"], answer: 2, explain: "The Great Wall was built in China." },
  { q: "How many days are in a leap year?", choices: ["365", "366", "364", "360"], answer: 1, explain: "A leap year has 366 days, with an extra day in February." },
  { q: "Which planet famously spins on its side?", choices: ["Mars", "Uranus", "Venus", "Neptune"], answer: 1, explain: "Uranus is tilted so far it rotates on its side." },
  { q: "What is the largest island in the world?", choices: ["Australia", "Greenland", "Madagascar", "Borneo"], answer: 1, explain: "Greenland is the world's largest island (Australia is a continent)." },
  { q: "Which country's flag features a red maple leaf?", choices: ["USA", "Canada", "Switzerland", "Norway"], answer: 1, explain: "Canada's flag has a red maple leaf." },
  { q: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], answer: 1, explain: "A hexagon has 6 sides." },
  { q: "Which is the tallest mountain above sea level?", choices: ["K2", "Mount Everest", "Mont Blanc", "Kilimanjaro"], answer: 1, explain: "Mount Everest is the highest mountain above sea level." },
  { q: "Who was the first person to walk on the Moon?", choices: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"], answer: 2, explain: "Neil Armstrong stepped onto the Moon in 1969." },
  { q: "What is the powerhouse of the cell?", choices: ["Nucleus", "Mitochondria", "Ribosome", "Membrane"], answer: 1, explain: "Mitochondria make energy for the cell." },
  { q: "Which ocean is the smallest?", choices: ["Arctic", "Indian", "Atlantic", "Southern"], answer: 0, explain: "The Arctic Ocean is the smallest." },
  { q: "What is 7 multiplied by 8?", choices: ["54", "56", "64", "48"], answer: 1, explain: "7 × 8 = 56." },
  { q: "What is the deepest place in the oceans called?", choices: ["Mariana Trench", "Grand Canyon", "Bermuda Triangle", "Dead Sea"], answer: 0, explain: "The Mariana Trench is the deepest known point in the oceans." },
  { q: "Which planet is so light it would float in water?", choices: ["Jupiter", "Saturn", "Neptune", "Mars"], answer: 1, explain: "Saturn is less dense than water, so it would float." },
  { q: "What is the capital of China?", choices: ["Shanghai", "Beijing", "Hong Kong", "Guangzhou"], answer: 1, explain: "Beijing is the capital of China." },
  { q: "Which is the fastest bird in the world?", choices: ["Eagle", "Peregrine falcon", "Ostrich", "Swift"], answer: 1, explain: "A diving peregrine falcon is the fastest bird." },
  { q: "What is the longest river in the world (traditionally)?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: 1, explain: "The Nile is traditionally considered the longest river." },
  { q: "What is the largest rainforest on Earth?", choices: ["Congo", "Amazon", "Borneo", "Daintree"], answer: 1, explain: "The Amazon is the world's largest rainforest." },
  { q: "Which is the longest mountain range in the world?", choices: ["Himalayas", "Alps", "Andes", "Rockies"], answer: 2, explain: "The Andes in South America is the longest mountain range." },
  { q: "What do we call the imaginary line around the middle of the Earth?", choices: ["Axis", "Equator", "Meridian", "Horizon"], answer: 1, explain: "The Equator circles the middle of the Earth." },
  { q: "Which metal is strongly attracted to a magnet?", choices: ["Gold", "Iron", "Copper", "Silver"], answer: 1, explain: "Iron is strongly magnetic." },
  { q: "Which is the tallest type of grass in the world?", choices: ["Sugarcane", "Bamboo", "Wheat", "Corn"], answer: 1, explain: "Bamboo is a grass and can grow taller than many trees." },
  { q: "Which is the smallest planet in our Solar System?", choices: ["Mars", "Mercury", "Venus", "Pluto"], answer: 1, explain: "Mercury is the smallest planet (Pluto is a dwarf planet)." },
  { q: "Which planet has the tallest volcano in the Solar System?", choices: ["Earth", "Mars", "Venus", "Jupiter"], answer: 1, explain: "Mars has Olympus Mons, the tallest known volcano." },
  { q: "What is 144 divided by 12?", choices: ["11", "12", "14", "10"], answer: 1, explain: "144 ÷ 12 = 12." },
  { q: "Which scientist is famous for the theory of gravity?", choices: ["Einstein", "Newton", "Darwin", "Galileo"], answer: 1, explain: "Isaac Newton described gravity." },
  { q: "What gas is used to make party balloons float?", choices: ["Oxygen", "Helium", "Hydrogen", "Nitrogen"], answer: 1, explain: "Helium is lighter than air, so the balloons float." },
  { q: "Which continent is the Sahara Desert on?", choices: ["Asia", "Africa", "Australia", "South America"], answer: 1, explain: "The Sahara is in Africa." },
  { q: "How many hearts does an octopus have?", choices: ["1", "2", "3", "4"], answer: 2, explain: "An octopus has three hearts." },
  { q: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: 2, explain: "Ottawa is Canada's capital." },
  { q: "Which country lies in both Europe and Asia?", choices: ["Greece", "Turkey", "Egypt", "Italy"], answer: 1, explain: "Turkey sits across both Europe and Asia." },
  { q: "What is the capital of India?", choices: ["Mumbai", "New Delhi", "Kolkata", "Chennai"], answer: 1, explain: "New Delhi is the capital of India." },
  { q: "Which animal is the largest that has ever lived?", choices: ["Elephant", "Blue whale", "Dinosaur", "Giraffe"], answer: 1, explain: "The blue whale is the largest animal ever known." },
  { q: "What is frozen carbon dioxide commonly called?", choices: ["Wet ice", "Dry ice", "Snow", "Frost"], answer: 1, explain: "Solid carbon dioxide is called dry ice." },
  { q: "Which country is shaped like a boot?", choices: ["Spain", "Italy", "Greece", "Portugal"], answer: 1, explain: "Italy is famously shaped like a boot." },
  { q: "Which is the largest kind of penguin?", choices: ["King penguin", "Emperor penguin", "Gentoo penguin", "Rockhopper"], answer: 1, explain: "The emperor penguin is the largest penguin." },
  { q: "What is the chemical symbol for water?", choices: ["CO2", "O2", "H2O", "NaCl"], answer: 2, explain: "Water is H₂O — two hydrogen and one oxygen." },
  { q: "What force slows down objects sliding across a surface?", choices: ["Gravity", "Friction", "Magnetism", "Pressure"], answer: 1, explain: "Friction resists sliding motion." },
  { q: "What is the largest lake in the world?", choices: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Lake Baikal"], answer: 1, explain: "The Caspian Sea is the world's largest lake." },
  { q: "Which is the largest hot desert in the world?", choices: ["Gobi", "Sahara", "Kalahari", "Mojave"], answer: 1, explain: "The Sahara is the largest hot desert." },
  { q: "What do you call a shape with eight sides?", choices: ["Hexagon", "Heptagon", "Octagon", "Pentagon"], answer: 2, explain: "An eight-sided shape is an octagon." },
  { q: "How many chambers does a human heart have?", choices: ["2", "3", "4", "5"], answer: 2, explain: "The human heart has 4 chambers." },
  { q: "Which continent has the most countries?", choices: ["Asia", "Africa", "Europe", "South America"], answer: 1, explain: "Africa has the most countries of any continent." },
  { q: "What is the largest internal organ in the human body?", choices: ["Heart", "Liver", "Brain", "Lungs"], answer: 1, explain: "The liver is the largest internal organ." },
  { q: "What is the biggest cat species in the world?", choices: ["Lion", "Tiger", "Leopard", "Jaguar"], answer: 1, explain: "The tiger is the largest wild cat." },
  { q: "Which planet takes the longest to travel around the Sun?", choices: ["Jupiter", "Saturn", "Neptune", "Mars"], answer: 2, explain: "Neptune, the farthest planet, has the longest orbit." },
  { q: "What is the tallest waterfall in the world?", choices: ["Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"], answer: 1, explain: "Angel Falls in Venezuela is the tallest waterfall." },
  { q: "In which country was paper first invented?", choices: ["Egypt", "China", "Greece", "India"], answer: 1, explain: "Paper was invented in ancient China." },
  { q: "What is the largest bird in the world?", choices: ["Eagle", "Ostrich", "Albatross", "Emu"], answer: 1, explain: "The ostrich is the largest living bird." },
  { q: "Which is the second-largest planet in the Solar System?", choices: ["Jupiter", "Saturn", "Neptune", "Uranus"], answer: 1, explain: "Saturn is the second-largest planet after Jupiter." },
  { q: "What is 9 squared (9 × 9)?", choices: ["72", "81", "90", "99"], answer: 1, explain: "9 × 9 = 81." },
  { q: "Which northern country is famous for its fjords and Viking history?", choices: ["Sweden", "Norway", "Denmark", "Finland"], answer: 1, explain: "Norway is known for its deep fjords and Viking past." },
  { q: "What is the largest coral reef system on Earth?", choices: ["Belize Barrier Reef", "Great Barrier Reef", "Red Sea Reef", "Maldives Reef"], answer: 1, explain: "Australia's Great Barrier Reef is the largest reef system." },
  { q: "Which sea is so salty that swimmers float on top of it?", choices: ["Red Sea", "Dead Sea", "Black Sea", "Caspian Sea"], answer: 1, explain: "The Dead Sea is so salty that people float easily." },
  { q: "What is frozen rain that falls as small ice balls called?", choices: ["Sleet", "Hail", "Frost", "Drizzle"], answer: 1, explain: "Hail is rain frozen into small balls of ice." },
  { q: "What is the fastest land animal?", choices: ["Lion", "Cheetah", "Horse", "Greyhound"], answer: 1, explain: "The cheetah is the fastest land animal." },
  { q: "Which of these is a source of light?", choices: ["The Moon", "A mirror", "The Sun", "A window"], answer: 2, explain: "The Sun makes its own light; the Moon only reflects it." },
  { q: "What is the capital of Germany?", choices: ["Munich", "Hamburg", "Berlin", "Frankfurt"], answer: 2, explain: "Berlin is the capital of Germany." },
  { q: "What is the largest country in Africa by area?", choices: ["Egypt", "Nigeria", "Algeria", "South Africa"], answer: 2, explain: "Algeria is the largest country in Africa." },
  { q: "How many teeth does a typical adult human have?", choices: ["28", "30", "32", "36"], answer: 2, explain: "Adults usually have 32 teeth." },
  { q: "Which metal is liquid at room temperature?", choices: ["Iron", "Mercury", "Copper", "Aluminium"], answer: 1, explain: "Mercury is a liquid metal at room temperature." },
  { q: "Which bird is the national symbol of the United States?", choices: ["Turkey", "Bald eagle", "Robin", "Owl"], answer: 1, explain: "The bald eagle is the national bird of the USA." },
  { q: "Which sea creature has eight arms?", choices: ["Squid", "Octopus", "Jellyfish", "Starfish"], answer: 1, explain: "An octopus has eight arms." },
  { q: "What causes day and night?", choices: ["The Earth spinning", "The Sun moving", "The Moon", "Clouds"], answer: 0, explain: "The Earth spinning on its axis causes day and night." },
  { q: "Which country has the most people?", choices: ["USA", "India", "Russia", "Brazil"], answer: 1, explain: "India has the largest population." },
  { q: "What is the main gas that plants take in?", choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Steam"], answer: 1, explain: "Plants take in carbon dioxide." },
  { q: "How many wings does a butterfly have?", choices: ["2", "4", "6", "8"], answer: 1, explain: "A butterfly has 4 wings." },
  { q: "Which is the biggest country by land area?", choices: ["China", "USA", "Russia", "Canada"], answer: 2, explain: "Russia is the largest country by area." },
  { q: "What do we call molten rock that erupts from a volcano?", choices: ["Magma", "Lava", "Ash", "Coal"], answer: 1, explain: "Once it reaches the surface, magma is called lava." },
  { q: "How many players are on a basketball team on the court?", choices: ["5", "6", "7", "11"], answer: 0, explain: "A basketball team has 5 players on court." },
  { q: "Which vitamin does sunlight help our body make?", choices: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], answer: 2, explain: "Sunlight helps our skin make Vitamin D." },
  { q: "Which ancient country first held the Olympic Games?", choices: ["Rome", "Greece", "Egypt", "Persia"], answer: 1, explain: "The ancient Olympics began in Greece." },
  { q: "Which animal is known for building dams?", choices: ["Otter", "Beaver", "Platypus", "Muskrat"], answer: 1, explain: "Beavers build dams across rivers." },
  { q: "What is 3 to the power of 3 (3 × 3 × 3)?", choices: ["9", "18", "27", "81"], answer: 2, explain: "3 × 3 × 3 = 27." },
  { q: "Which planet is famous for a giant red storm?", choices: ["Mars", "Jupiter", "Saturn", "Neptune"], answer: 1, explain: "Jupiter has the Great Red Spot, a huge storm." },
  { q: "In which country would you find the Colosseum?", choices: ["Greece", "Italy", "Spain", "France"], answer: 1, explain: "The Colosseum is in Rome, Italy." },
  { q: "What is the smallest country in the world?", choices: ["Monaco", "Vatican City", "Malta", "Nauru"], answer: 1, explain: "Vatican City is the smallest country." },
  { q: "What is the chemical symbol for gold?", choices: ["Go", "Gd", "Au", "Ag"], answer: 2, explain: "Gold's symbol is Au, from the Latin 'aurum'." },
  { q: "Which explorer reached the Americas in 1492?", choices: ["Ferdinand Magellan", "Christopher Columbus", "Vasco da Gama", "James Cook"], answer: 1, explain: "Columbus reached the Americas in 1492." },
  { q: "What is the currency used across most of Europe?", choices: ["Dollar", "Euro", "Pound", "Franc"], answer: 1, explain: "Most European Union countries use the euro." },
  { q: "What is the capital of the United States?", choices: ["New York", "Los Angeles", "Washington, D.C.", "Chicago"], answer: 2, explain: "Washington, D.C. is the capital of the USA." },
  { q: "What do you call the path a planet follows around the Sun?", choices: ["Axis", "Orbit", "Loop", "Ring"], answer: 1, explain: "A planet's path around the Sun is its orbit." },
  { q: "What is half of 250?", choices: ["100", "125", "150", "130"], answer: 1, explain: "Half of 250 is 125." },
  { q: "Which is NOT a planet?", choices: ["Neptune", "Uranus", "Pluto", "Saturn"], answer: 2, explain: "Pluto is now classed as a dwarf planet." },
  { q: "Which animal is the tallest in the world?", choices: ["Elephant", "Giraffe", "Camel", "Horse"], answer: 1, explain: "The giraffe is the tallest animal, thanks to its long neck." },
  { q: "Which country is home to the Taj Mahal?", choices: ["China", "India", "Pakistan", "Iran"], answer: 1, explain: "The Taj Mahal is in India." },
  { q: "What is the largest land animal?", choices: ["Rhino", "Hippo", "African elephant", "Giraffe"], answer: 2, explain: "The African elephant is the largest land animal." },
  { q: "How many degrees are in a right angle?", choices: ["45", "90", "180", "360"], answer: 1, explain: "A right angle is 90 degrees." },
  { q: "Which body part helps you keep your balance?", choices: ["Ears", "Eyes", "Nose", "Tongue"], answer: 0, explain: "The inner ear helps control balance." },
  { q: "Which South American country is a long, thin strip along the Pacific coast?", choices: ["Chile", "Peru", "Argentina", "Bolivia"], answer: 0, explain: "Chile is long and narrow along the west coast." },
  { q: "Which of these animals is an amphibian?", choices: ["Snake", "Frog", "Lizard", "Turtle"], answer: 1, explain: "Frogs are amphibians — they live in water and on land." },
  { q: "What is 12 × 12?", choices: ["120", "132", "144", "154"], answer: 2, explain: "12 × 12 = 144." },
  { q: "Which gas do we breathe out that plants use?", choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], answer: 1, explain: "We breathe out carbon dioxide, which plants use." },
  { q: "Which planet is named after the Roman god of war?", choices: ["Venus", "Mars", "Jupiter", "Mercury"], answer: 1, explain: "Mars is named after the Roman god of war." },
  { q: "Which is the largest country in South America?", choices: ["Argentina", "Peru", "Brazil", "Chile"], answer: 2, explain: "Brazil is the largest country in South America." },
];

export const ADULTS_QUESTIONS = [
  { q: "What is the chemical symbol for iron?", choices: ["Ir", "Fe", "In", "Io"], answer: 1, explain: "Iron's symbol is Fe, from the Latin 'ferrum'." },
  { q: "Who painted 'The Persistence of Memory', famous for its melting clocks?", choices: ["Pablo Picasso", "Salvador Dalí", "René Magritte", "Joan Miró"], answer: 1, explain: "Salvador Dalí painted The Persistence of Memory." },
  { q: "What is the capital of Australia?", choices: ["Sydney", "Melbourne", "Canberra", "Perth"], answer: 2, explain: "Canberra is Australia's capital, not Sydney." },
  { q: "In which year did World War II end?", choices: ["1943", "1944", "1945", "1946"], answer: 2, explain: "World War II ended in 1945." },
  { q: "Who wrote the novel 'The Brothers Karamazov'?", choices: ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"], answer: 1, explain: "Dostoevsky wrote The Brothers Karamazov." },
  { q: "What is the largest desert in the world?", choices: ["Sahara", "Arabian", "Antarctica", "Gobi"], answer: 2, explain: "Antarctica is the largest desert — a cold desert." },
  { q: "Which element has the atomic number 1?", choices: ["Helium", "Oxygen", "Hydrogen", "Carbon"], answer: 2, explain: "Hydrogen has atomic number 1." },
  { q: "What is the currency of Japan?", choices: ["Won", "Yuan", "Yen", "Ringgit"], answer: 2, explain: "Japan's currency is the yen." },
  { q: "Who developed the theory of general relativity?", choices: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"], answer: 2, explain: "Einstein developed general relativity." },
  { q: "The Great Barrier Reef lies off the coast of which country?", choices: ["Indonesia", "Australia", "Philippines", "Mexico"], answer: 1, explain: "The Great Barrier Reef is off Australia." },
  { q: "Which planet has the most moons (as currently known)?", choices: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: 1, explain: "Saturn currently has the most confirmed moons." },
  { q: "What is the capital of Turkey?", choices: ["Istanbul", "Ankara", "Izmir", "Bursa"], answer: 1, explain: "Ankara is Turkey's capital, not Istanbul." },
  { q: "Who wrote 'War and Peace'?", choices: ["Fyodor Dostoevsky", "Leo Tolstoy", "Anton Chekhov", "Ivan Turgenev"], answer: 1, explain: "Leo Tolstoy wrote War and Peace." },
  { q: "What is the chemical symbol for sodium?", choices: ["So", "Sd", "Na", "Sm"], answer: 2, explain: "Sodium's symbol is Na, from the Latin 'natrium'." },
  { q: "Approximately how fast does light travel in a vacuum?", choices: ["300 km/s", "3,000 km/s", "300,000 km/s", "30,000 km/s"], answer: 2, explain: "Light travels about 300,000 km per second." },
  { q: "Which composer wrote the 'Ode to Joy' in his Ninth Symphony?", choices: ["Mozart", "Bach", "Beethoven", "Brahms"], answer: 2, explain: "Beethoven wrote the Ninth Symphony with the Ode to Joy." },
  { q: "What is the smallest country in the world by area?", choices: ["Monaco", "Nauru", "Vatican City", "San Marino"], answer: 2, explain: "Vatican City is the smallest country." },
  { q: "In which year did the French Revolution begin?", choices: ["1776", "1789", "1804", "1815"], answer: 1, explain: "The French Revolution began in 1789." },
  { q: "Which organ produces insulin in the human body?", choices: ["Liver", "Pancreas", "Kidney", "Spleen"], answer: 1, explain: "The pancreas produces insulin." },
  { q: "What is the capital of Brazil?", choices: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], answer: 2, explain: "Brasília is Brazil's capital." },
  { q: "Which gas is most responsible for the greenhouse effect from human activity?", choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], answer: 1, explain: "Carbon dioxide is the main human-driven greenhouse gas." },
  { q: "Who painted 'The Night Watch'?", choices: ["Johannes Vermeer", "Rembrandt", "Peter Paul Rubens", "Frans Hals"], answer: 1, explain: "Rembrandt painted The Night Watch." },
  { q: "What is the chemical symbol for potassium?", choices: ["P", "Po", "K", "Pt"], answer: 2, explain: "Potassium's symbol is K, from the Latin 'kalium'." },
  { q: "Which river runs through the Grand Canyon?", choices: ["Mississippi", "Colorado", "Rio Grande", "Columbia"], answer: 1, explain: "The Colorado River carved the Grand Canyon." },
  { q: "How many bones are in the adult human body?", choices: ["198", "206", "212", "224"], answer: 1, explain: "The adult body has 206 bones." },
  { q: "Which country was formerly known as Persia?", choices: ["Iraq", "Iran", "Turkey", "Syria"], answer: 1, explain: "Iran was known as Persia until 1935." },
  { q: "Which is the most abundant metal in the Earth's crust?", choices: ["Iron", "Aluminium", "Copper", "Magnesium"], answer: 1, explain: "Aluminium is the most abundant metal in the crust." },
  { q: "Who wrote the novel '1984'?", choices: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], answer: 1, explain: "George Orwell wrote 1984." },
  { q: "What is the capital of Switzerland?", choices: ["Zurich", "Geneva", "Bern", "Basel"], answer: 2, explain: "Bern is the capital of Switzerland." },
  { q: "Which planet is the hottest in the Solar System?", choices: ["Mercury", "Venus", "Mars", "Jupiter"], answer: 1, explain: "Venus is hottest due to its thick, heat-trapping atmosphere." },
  { q: "In which modern country would you find the ancient ruins of Carthage?", choices: ["Egypt", "Tunisia", "Greece", "Turkey"], answer: 1, explain: "Ancient Carthage was near modern Tunis, in Tunisia." },
  { q: "What is the chemical symbol for lead?", choices: ["Le", "Ld", "Pb", "Pd"], answer: 2, explain: "Lead's symbol is Pb, from the Latin 'plumbum'." },
  { q: "Which scientist proposed the theory of evolution by natural selection?", choices: ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Carl Linnaeus"], answer: 1, explain: "Charles Darwin proposed natural selection." },
  { q: "What is the longest bone in the human body?", choices: ["Tibia", "Femur", "Humerus", "Spine"], answer: 1, explain: "The femur (thigh bone) is the longest bone." },
  { q: "In which year did the Berlin Wall fall?", choices: ["1987", "1989", "1991", "1993"], answer: 1, explain: "The Berlin Wall fell in 1989." },
  { q: "What is the capital of New Zealand?", choices: ["Auckland", "Wellington", "Christchurch", "Hamilton"], answer: 1, explain: "Wellington is New Zealand's capital, not Auckland." },
  { q: "Which is the longest river in the world (by many measures)?", choices: ["Nile", "Amazon", "Yangtze", "Mississippi"], answer: 0, explain: "The Nile is traditionally the longest, though the Amazon is close." },
  { q: "What does DNA stand for?", choices: ["Deoxyribonucleic acid", "Dinucleic acid", "Diribonucleic acid", "Deoxyribose acid"], answer: 0, explain: "DNA is deoxyribonucleic acid." },
  { q: "Who composed 'The Magic Flute'?", choices: ["Beethoven", "Mozart", "Handel", "Verdi"], answer: 1, explain: "Mozart composed The Magic Flute." },
  { q: "What is the tallest mountain in Africa?", choices: ["Mount Kenya", "Kilimanjaro", "Atlas", "Ras Dashen"], answer: 1, explain: "Mount Kilimanjaro is Africa's tallest mountain." },
  { q: "Which element is a noble gas?", choices: ["Chlorine", "Neon", "Sodium", "Sulfur"], answer: 1, explain: "Neon is a noble gas." },
  { q: "What is the capital of Argentina?", choices: ["Santiago", "Lima", "Buenos Aires", "Montevideo"], answer: 2, explain: "Buenos Aires is Argentina's capital." },
  { q: "Who wrote 'The Odyssey'?", choices: ["Virgil", "Homer", "Sophocles", "Plato"], answer: 1, explain: "Homer is credited with The Odyssey." },
  { q: "What is the powerhouse organelle where cellular respiration occurs?", choices: ["Nucleus", "Chloroplast", "Mitochondrion", "Golgi body"], answer: 2, explain: "The mitochondrion carries out cellular respiration." },
  { q: "Which country has the largest population in the world?", choices: ["China", "India", "United States", "Indonesia"], answer: 1, explain: "India is the most populous country." },
  { q: "What is the chemical symbol for silver?", choices: ["Si", "Sv", "Ag", "Au"], answer: 2, explain: "Silver's symbol is Ag, from the Latin 'argentum'." },
  { q: "The Sistine Chapel ceiling was painted by whom?", choices: ["Raphael", "Michelangelo", "Botticelli", "Caravaggio"], answer: 1, explain: "Michelangelo painted the Sistine Chapel ceiling." },
  { q: "The moon Titan, which has lakes of liquid methane, orbits which planet?", choices: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: 1, explain: "Titan is Saturn's largest moon." },
  { q: "Which ancient civilization built Machu Picchu?", choices: ["Aztec", "Maya", "Inca", "Olmec"], answer: 2, explain: "The Inca built Machu Picchu in Peru." },
  { q: "What is the capital of Norway?", choices: ["Bergen", "Oslo", "Stavanger", "Trondheim"], answer: 1, explain: "Oslo is the capital of Norway." },
  { q: "Which planet spins on its side (rotational axis tilted ~98°)?", choices: ["Neptune", "Uranus", "Saturn", "Mars"], answer: 1, explain: "Uranus rotates on its side." },
  { q: "Who is credited with discovering penicillin?", choices: ["Marie Curie", "Alexander Fleming", "Jonas Salk", "Robert Koch"], answer: 1, explain: "Alexander Fleming discovered penicillin in 1928." },
  { q: "What is the pH of pure water at room temperature?", choices: ["0", "7", "10", "14"], answer: 1, explain: "Pure water is neutral, with a pH of 7." },
  { q: "In which country would you find the ancient city of Petra?", choices: ["Egypt", "Jordan", "Lebanon", "Syria"], answer: 1, explain: "Petra is in Jordan." },
  { q: "Who wrote 'Pride and Prejudice'?", choices: ["Charlotte Brontë", "Jane Austen", "Emily Brontë", "Mary Shelley"], answer: 1, explain: "Jane Austen wrote Pride and Prejudice." },
  { q: "What is the chemical symbol for mercury?", choices: ["Me", "Mr", "Hg", "Mc"], answer: 2, explain: "Mercury's symbol is Hg, from 'hydrargyrum'." },
  { q: "Which sea is the saltiest large body of water, so buoyant you float easily?", choices: ["Red Sea", "Dead Sea", "Black Sea", "Caspian Sea"], answer: 1, explain: "The Dead Sea is extremely salty and buoyant." },
  { q: "What is the capital of South Korea?", choices: ["Busan", "Seoul", "Incheon", "Daegu"], answer: 1, explain: "Seoul is South Korea's capital." },
  { q: "How many strings does a standard violin have?", choices: ["4", "5", "6", "7"], answer: 0, explain: "A violin has 4 strings." },
  { q: "Which gas makes up roughly 21% of Earth's atmosphere?", choices: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"], answer: 1, explain: "Oxygen is about 21% of the atmosphere." },
  { q: "Who painted 'Guernica'?", choices: ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Diego Rivera"], answer: 1, explain: "Picasso painted Guernica." },
  { q: "What is the capital of Egypt?", choices: ["Alexandria", "Cairo", "Luxor", "Aswan"], answer: 1, explain: "Cairo is the capital of Egypt." },
  { q: "The speed of sound in air is closest to which value?", choices: ["34 m/s", "343 m/s", "3,430 m/s", "34,300 m/s"], answer: 1, explain: "Sound travels about 343 m/s in air." },
  { q: "Which planet is known as the 'Morning Star' or 'Evening Star'?", choices: ["Mars", "Venus", "Mercury", "Jupiter"], answer: 1, explain: "Venus is often seen near dawn or dusk." },
  { q: "Who wrote 'Crime and Punishment'?", choices: ["Leo Tolstoy", "Fyodor Dostoevsky", "Nikolai Gogol", "Boris Pasternak"], answer: 1, explain: "Dostoevsky wrote Crime and Punishment." },
  { q: "What is the currency of India?", choices: ["Taka", "Rupee", "Rupiah", "Ringgit"], answer: 1, explain: "India's currency is the rupee." },
  { q: "Which vitamin is produced when skin is exposed to sunlight?", choices: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], answer: 3, explain: "Sunlight helps the body make Vitamin D." },
  { q: "Which scientist formulated the three laws of planetary motion?", choices: ["Copernicus", "Johannes Kepler", "Tycho Brahe", "Galileo"], answer: 1, explain: "Kepler formulated the laws of planetary motion." },
  { q: "In which year did the first successful powered flight by the Wright brothers take place?", choices: ["1899", "1903", "1912", "1920"], answer: 1, explain: "The Wright brothers flew in 1903." },
  { q: "What is the capital of Greece?", choices: ["Thessaloniki", "Athens", "Sparta", "Patras"], answer: 1, explain: "Athens is the capital of Greece." },
  { q: "Which blood type is known as the universal donor?", choices: ["AB positive", "O negative", "A positive", "B negative"], answer: 1, explain: "O negative is the universal red-cell donor." },
  { q: "Who wrote 'The Divine Comedy'?", choices: ["Petrarch", "Dante Alighieri", "Boccaccio", "Machiavelli"], answer: 1, explain: "Dante wrote The Divine Comedy." },
  { q: "What is the atomic number of carbon?", choices: ["4", "6", "8", "12"], answer: 1, explain: "Carbon has atomic number 6." },
  { q: "Which country gifted the Statue of Liberty to the United States?", choices: ["United Kingdom", "France", "Spain", "Italy"], answer: 1, explain: "France gifted the Statue of Liberty." },
  { q: "What is the capital of Portugal?", choices: ["Porto", "Lisbon", "Faro", "Braga"], answer: 1, explain: "Lisbon is the capital of Portugal." },
  { q: "Which planet has a day longer than its year?", choices: ["Mercury", "Venus", "Mars", "Neptune"], answer: 1, explain: "Venus rotates so slowly its day is longer than its year." },
  { q: "Who is famous for studying falling bodies (traditionally at the Leaning Tower of Pisa)?", choices: ["Newton", "Galileo", "Copernicus", "Kepler"], answer: 1, explain: "Galileo is famous for studying falling bodies." },
  { q: "What is the largest species of shark?", choices: ["Great white", "Whale shark", "Tiger shark", "Hammerhead"], answer: 1, explain: "The whale shark is the largest shark (and fish)." },
  { q: "What is the capital of Kenya?", choices: ["Mombasa", "Nairobi", "Kisumu", "Nakuru"], answer: 1, explain: "Nairobi is the capital of Kenya." },
  { q: "The Pythagorean theorem relates the sides of which shape?", choices: ["Circle", "Right triangle", "Square", "Pentagon"], answer: 1, explain: "It relates the sides of a right-angled triangle." },
  { q: "Which artist cut off part of his own ear?", choices: ["Monet", "Van Gogh", "Renoir", "Manet"], answer: 1, explain: "Vincent van Gogh famously cut off part of his ear." },
  { q: "What is the chemical symbol for tin?", choices: ["Ti", "Tn", "Sn", "T"], answer: 2, explain: "Tin's symbol is Sn, from the Latin 'stannum'." },
  { q: "Which country has the most time zones?", choices: ["Russia", "United States", "France", "China"], answer: 2, explain: "France, counting its overseas territories, spans the most time zones." },
  { q: "Who wrote 'One Hundred Years of Solitude'?", choices: ["Jorge Luis Borges", "Gabriel García Márquez", "Pablo Neruda", "Mario Vargas Llosa"], answer: 1, explain: "García Márquez wrote One Hundred Years of Solitude." },
  { q: "What is the most abundant element in the universe?", choices: ["Oxygen", "Hydrogen", "Helium", "Carbon"], answer: 1, explain: "Hydrogen is the most abundant element." },
  { q: "The Amazon River is mostly in which country?", choices: ["Peru", "Colombia", "Brazil", "Venezuela"], answer: 2, explain: "Most of the Amazon flows through Brazil." },
  { q: "What is the capital of the Netherlands?", choices: ["Rotterdam", "The Hague", "Amsterdam", "Utrecht"], answer: 2, explain: "Amsterdam is the capital (though the government sits in The Hague)." },
  { q: "Which planet is nicknamed the 'Ice Giant' along with Neptune?", choices: ["Saturn", "Uranus", "Jupiter", "Mars"], answer: 1, explain: "Uranus and Neptune are the ice giants." },
  { q: "Who painted 'The Scream'?", choices: ["Gustav Klimt", "Edvard Munch", "Egon Schiele", "James Ensor"], answer: 1, explain: "Edvard Munch painted The Scream." },
  { q: "What is the freezing point of water in Fahrenheit?", choices: ["0°F", "32°F", "100°F", "-32°F"], answer: 1, explain: "Water freezes at 32°F." },
  { q: "Which empire was ruled by Julius Caesar's heirs?", choices: ["Greek", "Roman", "Ottoman", "Byzantine"], answer: 1, explain: "Caesar's heirs ruled the Roman Empire." },
  { q: "What is the capital of Sweden?", choices: ["Gothenburg", "Stockholm", "Malmö", "Uppsala"], answer: 1, explain: "Stockholm is the capital of Sweden." },
  { q: "How many players are on a cricket team?", choices: ["9", "10", "11", "12"], answer: 2, explain: "A cricket team has 11 players." },
  { q: "Which scientist formulated the three laws of motion?", choices: ["Galileo", "Isaac Newton", "Albert Einstein", "James Clerk Maxwell"], answer: 1, explain: "Newton formulated the three laws of motion." },
  { q: "What is the capital of Thailand?", choices: ["Chiang Mai", "Bangkok", "Phuket", "Pattaya"], answer: 1, explain: "Bangkok is the capital of Thailand." },
  { q: "Which metal has the chemical symbol Cu?", choices: ["Chromium", "Copper", "Cobalt", "Cadmium"], answer: 1, explain: "Cu is copper, from the Latin 'cuprum'." },
  { q: "Who wrote 'Don Quixote'?", choices: ["Miguel de Cervantes", "Lope de Vega", "Federico García Lorca", "Gabriel García Márquez"], answer: 0, explain: "Cervantes wrote Don Quixote." },
  { q: "What is the largest organ of the human body?", choices: ["Liver", "Skin", "Lungs", "Brain"], answer: 1, explain: "The skin is the body's largest organ." },
  { q: "In which modern country was the philosopher Confucius born?", choices: ["Japan", "China", "Korea", "Vietnam"], answer: 1, explain: "Confucius was born in China." },
  { q: "What is the capital of Ireland?", choices: ["Cork", "Dublin", "Galway", "Belfast"], answer: 1, explain: "Dublin is the capital of the Republic of Ireland." },
];

// Draw `n` distinct questions at random from the chosen pool ("kids"|"adults"),
// each with its answer choices shuffled so the correct option's position varies.
export function drawQuizQuestions(n = 3, mode = "kids", rng = Math.random) {
  const pool = [...(mode === "adults" ? ADULTS_QUESTIONS : KIDS_QUESTIONS)];
  const out = [];
  for (let i = 0; i < n && pool.length; i++) {
    const src = pool.splice(Math.floor(rng() * pool.length), 1)[0];
    const correct = src.choices[src.answer];
    const choices = [...src.choices];
    for (let j = choices.length - 1; j > 0; j--) {
      const k = Math.floor(rng() * (j + 1));
      [choices[j], choices[k]] = [choices[k], choices[j]];
    }
    out.push({ q: src.q, choices, answer: choices.indexOf(correct), explain: src.explain });
  }
  return out;
}
